wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1708637009.025278
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.12
      5: 0.14.0
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 75
dataset:
  desc: null
  value: heart_2022_no_nans
epochs:
  desc: null
  value: 5
l2_norm_clip:
  desc: null
  value: 0.2938445623461257
learning_rate:
  desc: null
  value: 8.426865981818244e-06
noise_multiplier:
  desc: null
  value: 0.37666007005512103
