wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.14.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1708638151.297899
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 2
      - 16
      - 23
      - 37
      4: 3.9.12
      5: 0.14.0
      8:
      - 3
      - 5
batch_size:
  desc: null
  value: 30
dataset:
  desc: null
  value: heart_2022_no_nans
epochs:
  desc: null
  value: 10
l2_norm_clip:
  desc: null
  value: 2.3892122244070055
learning_rate:
  desc: null
  value: 4.326304709372301e-05
noise_multiplier:
  desc: null
  value: 5.642984809460576
