wandb_version: 1

learning_rate:
  desc: null
  value: 1.0e-05
dataset:
  desc: null
  value: heart_2022_no_nans
epochs:
  desc: null
  value: 6
_wandb:
  desc: null
  value:
    python_version: 3.9.12
    cli_version: 0.16.3
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1708293745.461702
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.12
      5: 0.16.3
      8:
      - 3
      - 5
      13: windows-amd64
